# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/dmitry/Qt/Tools/CMake/bin/cmake

# The command to remove a file.
RM = /home/dmitry/Qt/Tools/CMake/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dmitry/Courseproject-Modelling-road-traffic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dmitry/Courseproject-Modelling-road-traffic

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/dmitry/Qt/Tools/CMake/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/dmitry/Qt/Tools/CMake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dmitry/Courseproject-Modelling-road-traffic/CMakeFiles /home/dmitry/Courseproject-Modelling-road-traffic//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dmitry/Courseproject-Modelling-road-traffic/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gui

# Build rule for target.
gui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gui
.PHONY : gui

# fast build rule for target.
gui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/build
.PHONY : gui/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named gui_autogen

# Build rule for target.
gui_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gui_autogen
.PHONY : gui_autogen

# fast build rule for target.
gui_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui_autogen.dir/build.make CMakeFiles/gui_autogen.dir/build
.PHONY : gui_autogen/fast

QtApp/Item.o: QtApp/Item.cpp.o

.PHONY : QtApp/Item.o

# target to build an object file
QtApp/Item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/QtApp/Item.cpp.o
.PHONY : QtApp/Item.cpp.o

QtApp/Item.i: QtApp/Item.cpp.i

.PHONY : QtApp/Item.i

# target to preprocess a source file
QtApp/Item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/QtApp/Item.cpp.i
.PHONY : QtApp/Item.cpp.i

QtApp/Item.s: QtApp/Item.cpp.s

.PHONY : QtApp/Item.s

# target to generate assembly for a file
QtApp/Item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/QtApp/Item.cpp.s
.PHONY : QtApp/Item.cpp.s

QtApp/Mainwindow.o: QtApp/Mainwindow.cpp.o

.PHONY : QtApp/Mainwindow.o

# target to build an object file
QtApp/Mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/QtApp/Mainwindow.cpp.o
.PHONY : QtApp/Mainwindow.cpp.o

QtApp/Mainwindow.i: QtApp/Mainwindow.cpp.i

.PHONY : QtApp/Mainwindow.i

# target to preprocess a source file
QtApp/Mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/QtApp/Mainwindow.cpp.i
.PHONY : QtApp/Mainwindow.cpp.i

QtApp/Mainwindow.s: QtApp/Mainwindow.cpp.s

.PHONY : QtApp/Mainwindow.s

# target to generate assembly for a file
QtApp/Mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/QtApp/Mainwindow.cpp.s
.PHONY : QtApp/Mainwindow.cpp.s

QtApp/Workspace.o: QtApp/Workspace.cpp.o

.PHONY : QtApp/Workspace.o

# target to build an object file
QtApp/Workspace.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/QtApp/Workspace.cpp.o
.PHONY : QtApp/Workspace.cpp.o

QtApp/Workspace.i: QtApp/Workspace.cpp.i

.PHONY : QtApp/Workspace.i

# target to preprocess a source file
QtApp/Workspace.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/QtApp/Workspace.cpp.i
.PHONY : QtApp/Workspace.cpp.i

QtApp/Workspace.s: QtApp/Workspace.cpp.s

.PHONY : QtApp/Workspace.s

# target to generate assembly for a file
QtApp/Workspace.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/QtApp/Workspace.cpp.s
.PHONY : QtApp/Workspace.cpp.s

QtApp/WorkspaceScene.o: QtApp/WorkspaceScene.cpp.o

.PHONY : QtApp/WorkspaceScene.o

# target to build an object file
QtApp/WorkspaceScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/QtApp/WorkspaceScene.cpp.o
.PHONY : QtApp/WorkspaceScene.cpp.o

QtApp/WorkspaceScene.i: QtApp/WorkspaceScene.cpp.i

.PHONY : QtApp/WorkspaceScene.i

# target to preprocess a source file
QtApp/WorkspaceScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/QtApp/WorkspaceScene.cpp.i
.PHONY : QtApp/WorkspaceScene.cpp.i

QtApp/WorkspaceScene.s: QtApp/WorkspaceScene.cpp.s

.PHONY : QtApp/WorkspaceScene.s

# target to generate assembly for a file
QtApp/WorkspaceScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/QtApp/WorkspaceScene.cpp.s
.PHONY : QtApp/WorkspaceScene.cpp.s

QtApp/main.o: QtApp/main.cpp.o

.PHONY : QtApp/main.o

# target to build an object file
QtApp/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/QtApp/main.cpp.o
.PHONY : QtApp/main.cpp.o

QtApp/main.i: QtApp/main.cpp.i

.PHONY : QtApp/main.i

# target to preprocess a source file
QtApp/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/QtApp/main.cpp.i
.PHONY : QtApp/main.cpp.i

QtApp/main.s: QtApp/main.cpp.s

.PHONY : QtApp/main.s

# target to generate assembly for a file
QtApp/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/QtApp/main.cpp.s
.PHONY : QtApp/main.cpp.s

gui_autogen/mocs_compilation.o: gui_autogen/mocs_compilation.cpp.o

.PHONY : gui_autogen/mocs_compilation.o

# target to build an object file
gui_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/gui_autogen/mocs_compilation.cpp.o
.PHONY : gui_autogen/mocs_compilation.cpp.o

gui_autogen/mocs_compilation.i: gui_autogen/mocs_compilation.cpp.i

.PHONY : gui_autogen/mocs_compilation.i

# target to preprocess a source file
gui_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/gui_autogen/mocs_compilation.cpp.i
.PHONY : gui_autogen/mocs_compilation.cpp.i

gui_autogen/mocs_compilation.s: gui_autogen/mocs_compilation.cpp.s

.PHONY : gui_autogen/mocs_compilation.s

# target to generate assembly for a file
gui_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/gui_autogen/mocs_compilation.cpp.s
.PHONY : gui_autogen/mocs_compilation.cpp.s

src/ModelApplication.o: src/ModelApplication.cpp.o

.PHONY : src/ModelApplication.o

# target to build an object file
src/ModelApplication.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ModelApplication.cpp.o
.PHONY : src/ModelApplication.cpp.o

src/ModelApplication.i: src/ModelApplication.cpp.i

.PHONY : src/ModelApplication.i

# target to preprocess a source file
src/ModelApplication.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ModelApplication.cpp.i
.PHONY : src/ModelApplication.cpp.i

src/ModelApplication.s: src/ModelApplication.cpp.s

.PHONY : src/ModelApplication.s

# target to generate assembly for a file
src/ModelApplication.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ModelApplication.cpp.s
.PHONY : src/ModelApplication.cpp.s

src/OpenglLayer.o: src/OpenglLayer.cpp.o

.PHONY : src/OpenglLayer.o

# target to build an object file
src/OpenglLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/OpenglLayer.cpp.o
.PHONY : src/OpenglLayer.cpp.o

src/OpenglLayer.i: src/OpenglLayer.cpp.i

.PHONY : src/OpenglLayer.i

# target to preprocess a source file
src/OpenglLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/OpenglLayer.cpp.i
.PHONY : src/OpenglLayer.cpp.i

src/OpenglLayer.s: src/OpenglLayer.cpp.s

.PHONY : src/OpenglLayer.s

# target to generate assembly for a file
src/OpenglLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/OpenglLayer.cpp.s
.PHONY : src/OpenglLayer.cpp.s

src/core/Car.o: src/core/Car.cpp.o

.PHONY : src/core/Car.o

# target to build an object file
src/core/Car.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Car.cpp.o
.PHONY : src/core/Car.cpp.o

src/core/Car.i: src/core/Car.cpp.i

.PHONY : src/core/Car.i

# target to preprocess a source file
src/core/Car.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Car.cpp.i
.PHONY : src/core/Car.cpp.i

src/core/Car.s: src/core/Car.cpp.s

.PHONY : src/core/Car.s

# target to generate assembly for a file
src/core/Car.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Car.cpp.s
.PHONY : src/core/Car.cpp.s

src/core/ForceGenerator.o: src/core/ForceGenerator.cpp.o

.PHONY : src/core/ForceGenerator.o

# target to build an object file
src/core/ForceGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/ForceGenerator.cpp.o
.PHONY : src/core/ForceGenerator.cpp.o

src/core/ForceGenerator.i: src/core/ForceGenerator.cpp.i

.PHONY : src/core/ForceGenerator.i

# target to preprocess a source file
src/core/ForceGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/ForceGenerator.cpp.i
.PHONY : src/core/ForceGenerator.cpp.i

src/core/ForceGenerator.s: src/core/ForceGenerator.cpp.s

.PHONY : src/core/ForceGenerator.s

# target to generate assembly for a file
src/core/ForceGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/ForceGenerator.cpp.s
.PHONY : src/core/ForceGenerator.cpp.s

src/core/MDLParser.o: src/core/MDLParser.cpp.o

.PHONY : src/core/MDLParser.o

# target to build an object file
src/core/MDLParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/MDLParser.cpp.o
.PHONY : src/core/MDLParser.cpp.o

src/core/MDLParser.i: src/core/MDLParser.cpp.i

.PHONY : src/core/MDLParser.i

# target to preprocess a source file
src/core/MDLParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/MDLParser.cpp.i
.PHONY : src/core/MDLParser.cpp.i

src/core/MDLParser.s: src/core/MDLParser.cpp.s

.PHONY : src/core/MDLParser.s

# target to generate assembly for a file
src/core/MDLParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/MDLParser.cpp.s
.PHONY : src/core/MDLParser.cpp.s

src/core/Particle.o: src/core/Particle.cpp.o

.PHONY : src/core/Particle.o

# target to build an object file
src/core/Particle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Particle.cpp.o
.PHONY : src/core/Particle.cpp.o

src/core/Particle.i: src/core/Particle.cpp.i

.PHONY : src/core/Particle.i

# target to preprocess a source file
src/core/Particle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Particle.cpp.i
.PHONY : src/core/Particle.cpp.i

src/core/Particle.s: src/core/Particle.cpp.s

.PHONY : src/core/Particle.s

# target to generate assembly for a file
src/core/Particle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Particle.cpp.s
.PHONY : src/core/Particle.cpp.s

src/core/Road.o: src/core/Road.cpp.o

.PHONY : src/core/Road.o

# target to build an object file
src/core/Road.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Road.cpp.o
.PHONY : src/core/Road.cpp.o

src/core/Road.i: src/core/Road.cpp.i

.PHONY : src/core/Road.i

# target to preprocess a source file
src/core/Road.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Road.cpp.i
.PHONY : src/core/Road.cpp.i

src/core/Road.s: src/core/Road.cpp.s

.PHONY : src/core/Road.s

# target to generate assembly for a file
src/core/Road.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Road.cpp.s
.PHONY : src/core/Road.cpp.s

src/core/TrafficLight.o: src/core/TrafficLight.cpp.o

.PHONY : src/core/TrafficLight.o

# target to build an object file
src/core/TrafficLight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/TrafficLight.cpp.o
.PHONY : src/core/TrafficLight.cpp.o

src/core/TrafficLight.i: src/core/TrafficLight.cpp.i

.PHONY : src/core/TrafficLight.i

# target to preprocess a source file
src/core/TrafficLight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/TrafficLight.cpp.i
.PHONY : src/core/TrafficLight.cpp.i

src/core/TrafficLight.s: src/core/TrafficLight.cpp.s

.PHONY : src/core/TrafficLight.s

# target to generate assembly for a file
src/core/TrafficLight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/TrafficLight.cpp.s
.PHONY : src/core/TrafficLight.cpp.s

src/core/Vector.o: src/core/Vector.cpp.o

.PHONY : src/core/Vector.o

# target to build an object file
src/core/Vector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Vector.cpp.o
.PHONY : src/core/Vector.cpp.o

src/core/Vector.i: src/core/Vector.cpp.i

.PHONY : src/core/Vector.i

# target to preprocess a source file
src/core/Vector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Vector.cpp.i
.PHONY : src/core/Vector.cpp.i

src/core/Vector.s: src/core/Vector.cpp.s

.PHONY : src/core/Vector.s

# target to generate assembly for a file
src/core/Vector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Vector.cpp.s
.PHONY : src/core/Vector.cpp.s

src/glfw/Window.o: src/glfw/Window.cpp.o

.PHONY : src/glfw/Window.o

# target to build an object file
src/glfw/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/glfw/Window.cpp.o
.PHONY : src/glfw/Window.cpp.o

src/glfw/Window.i: src/glfw/Window.cpp.i

.PHONY : src/glfw/Window.i

# target to preprocess a source file
src/glfw/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/glfw/Window.cpp.i
.PHONY : src/glfw/Window.cpp.i

src/glfw/Window.s: src/glfw/Window.cpp.s

.PHONY : src/glfw/Window.s

# target to generate assembly for a file
src/glfw/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/glfw/Window.cpp.s
.PHONY : src/glfw/Window.cpp.s

src/imgui/ImguiLayer.o: src/imgui/ImguiLayer.cpp.o

.PHONY : src/imgui/ImguiLayer.o

# target to build an object file
src/imgui/ImguiLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/ImguiLayer.cpp.o
.PHONY : src/imgui/ImguiLayer.cpp.o

src/imgui/ImguiLayer.i: src/imgui/ImguiLayer.cpp.i

.PHONY : src/imgui/ImguiLayer.i

# target to preprocess a source file
src/imgui/ImguiLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/ImguiLayer.cpp.i
.PHONY : src/imgui/ImguiLayer.cpp.i

src/imgui/ImguiLayer.s: src/imgui/ImguiLayer.cpp.s

.PHONY : src/imgui/ImguiLayer.s

# target to generate assembly for a file
src/imgui/ImguiLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/imgui/ImguiLayer.cpp.s
.PHONY : src/imgui/ImguiLayer.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/opengl/Buffer.o: src/opengl/Buffer.cpp.o

.PHONY : src/opengl/Buffer.o

# target to build an object file
src/opengl/Buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/Buffer.cpp.o
.PHONY : src/opengl/Buffer.cpp.o

src/opengl/Buffer.i: src/opengl/Buffer.cpp.i

.PHONY : src/opengl/Buffer.i

# target to preprocess a source file
src/opengl/Buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/Buffer.cpp.i
.PHONY : src/opengl/Buffer.cpp.i

src/opengl/Buffer.s: src/opengl/Buffer.cpp.s

.PHONY : src/opengl/Buffer.s

# target to generate assembly for a file
src/opengl/Buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/Buffer.cpp.s
.PHONY : src/opengl/Buffer.cpp.s

src/opengl/OrtographicCamera.o: src/opengl/OrtographicCamera.cpp.o

.PHONY : src/opengl/OrtographicCamera.o

# target to build an object file
src/opengl/OrtographicCamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/OrtographicCamera.cpp.o
.PHONY : src/opengl/OrtographicCamera.cpp.o

src/opengl/OrtographicCamera.i: src/opengl/OrtographicCamera.cpp.i

.PHONY : src/opengl/OrtographicCamera.i

# target to preprocess a source file
src/opengl/OrtographicCamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/OrtographicCamera.cpp.i
.PHONY : src/opengl/OrtographicCamera.cpp.i

src/opengl/OrtographicCamera.s: src/opengl/OrtographicCamera.cpp.s

.PHONY : src/opengl/OrtographicCamera.s

# target to generate assembly for a file
src/opengl/OrtographicCamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/OrtographicCamera.cpp.s
.PHONY : src/opengl/OrtographicCamera.cpp.s

src/opengl/Renderer.o: src/opengl/Renderer.cpp.o

.PHONY : src/opengl/Renderer.o

# target to build an object file
src/opengl/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/Renderer.cpp.o
.PHONY : src/opengl/Renderer.cpp.o

src/opengl/Renderer.i: src/opengl/Renderer.cpp.i

.PHONY : src/opengl/Renderer.i

# target to preprocess a source file
src/opengl/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/Renderer.cpp.i
.PHONY : src/opengl/Renderer.cpp.i

src/opengl/Renderer.s: src/opengl/Renderer.cpp.s

.PHONY : src/opengl/Renderer.s

# target to generate assembly for a file
src/opengl/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/Renderer.cpp.s
.PHONY : src/opengl/Renderer.cpp.s

src/opengl/Shader.o: src/opengl/Shader.cpp.o

.PHONY : src/opengl/Shader.o

# target to build an object file
src/opengl/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/Shader.cpp.o
.PHONY : src/opengl/Shader.cpp.o

src/opengl/Shader.i: src/opengl/Shader.cpp.i

.PHONY : src/opengl/Shader.i

# target to preprocess a source file
src/opengl/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/Shader.cpp.i
.PHONY : src/opengl/Shader.cpp.i

src/opengl/Shader.s: src/opengl/Shader.cpp.s

.PHONY : src/opengl/Shader.s

# target to generate assembly for a file
src/opengl/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/Shader.cpp.s
.PHONY : src/opengl/Shader.cpp.s

src/opengl/Texture.o: src/opengl/Texture.cpp.o

.PHONY : src/opengl/Texture.o

# target to build an object file
src/opengl/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/Texture.cpp.o
.PHONY : src/opengl/Texture.cpp.o

src/opengl/Texture.i: src/opengl/Texture.cpp.i

.PHONY : src/opengl/Texture.i

# target to preprocess a source file
src/opengl/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/Texture.cpp.i
.PHONY : src/opengl/Texture.cpp.i

src/opengl/Texture.s: src/opengl/Texture.cpp.s

.PHONY : src/opengl/Texture.s

# target to generate assembly for a file
src/opengl/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/Texture.cpp.s
.PHONY : src/opengl/Texture.cpp.s

src/opengl/VertexArray.o: src/opengl/VertexArray.cpp.o

.PHONY : src/opengl/VertexArray.o

# target to build an object file
src/opengl/VertexArray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/VertexArray.cpp.o
.PHONY : src/opengl/VertexArray.cpp.o

src/opengl/VertexArray.i: src/opengl/VertexArray.cpp.i

.PHONY : src/opengl/VertexArray.i

# target to preprocess a source file
src/opengl/VertexArray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/VertexArray.cpp.i
.PHONY : src/opengl/VertexArray.cpp.i

src/opengl/VertexArray.s: src/opengl/VertexArray.cpp.s

.PHONY : src/opengl/VertexArray.s

# target to generate assembly for a file
src/opengl/VertexArray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/VertexArray.cpp.s
.PHONY : src/opengl/VertexArray.cpp.s

src/opengl/debug.o: src/opengl/debug.cpp.o

.PHONY : src/opengl/debug.o

# target to build an object file
src/opengl/debug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/debug.cpp.o
.PHONY : src/opengl/debug.cpp.o

src/opengl/debug.i: src/opengl/debug.cpp.i

.PHONY : src/opengl/debug.i

# target to preprocess a source file
src/opengl/debug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/debug.cpp.i
.PHONY : src/opengl/debug.cpp.i

src/opengl/debug.s: src/opengl/debug.cpp.s

.PHONY : src/opengl/debug.s

# target to generate assembly for a file
src/opengl/debug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/opengl/debug.cpp.s
.PHONY : src/opengl/debug.cpp.s

src/pch.o: src/pch.cpp.o

.PHONY : src/pch.o

# target to build an object file
src/pch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/pch.cpp.o
.PHONY : src/pch.cpp.o

src/pch.i: src/pch.cpp.i

.PHONY : src/pch.i

# target to preprocess a source file
src/pch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/pch.cpp.i
.PHONY : src/pch.cpp.i

src/pch.s: src/pch.cpp.s

.PHONY : src/pch.s

# target to generate assembly for a file
src/pch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/pch.cpp.s
.PHONY : src/pch.cpp.s

src/vendor/imgui/imgui.o: src/vendor/imgui/imgui.cpp.o

.PHONY : src/vendor/imgui/imgui.o

# target to build an object file
src/vendor/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui.cpp.o
.PHONY : src/vendor/imgui/imgui.cpp.o

src/vendor/imgui/imgui.i: src/vendor/imgui/imgui.cpp.i

.PHONY : src/vendor/imgui/imgui.i

# target to preprocess a source file
src/vendor/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui.cpp.i
.PHONY : src/vendor/imgui/imgui.cpp.i

src/vendor/imgui/imgui.s: src/vendor/imgui/imgui.cpp.s

.PHONY : src/vendor/imgui/imgui.s

# target to generate assembly for a file
src/vendor/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui.cpp.s
.PHONY : src/vendor/imgui/imgui.cpp.s

src/vendor/imgui/imgui_demo.o: src/vendor/imgui/imgui_demo.cpp.o

.PHONY : src/vendor/imgui/imgui_demo.o

# target to build an object file
src/vendor/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_demo.cpp.o
.PHONY : src/vendor/imgui/imgui_demo.cpp.o

src/vendor/imgui/imgui_demo.i: src/vendor/imgui/imgui_demo.cpp.i

.PHONY : src/vendor/imgui/imgui_demo.i

# target to preprocess a source file
src/vendor/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_demo.cpp.i
.PHONY : src/vendor/imgui/imgui_demo.cpp.i

src/vendor/imgui/imgui_demo.s: src/vendor/imgui/imgui_demo.cpp.s

.PHONY : src/vendor/imgui/imgui_demo.s

# target to generate assembly for a file
src/vendor/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_demo.cpp.s
.PHONY : src/vendor/imgui/imgui_demo.cpp.s

src/vendor/imgui/imgui_draw.o: src/vendor/imgui/imgui_draw.cpp.o

.PHONY : src/vendor/imgui/imgui_draw.o

# target to build an object file
src/vendor/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_draw.cpp.o
.PHONY : src/vendor/imgui/imgui_draw.cpp.o

src/vendor/imgui/imgui_draw.i: src/vendor/imgui/imgui_draw.cpp.i

.PHONY : src/vendor/imgui/imgui_draw.i

# target to preprocess a source file
src/vendor/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_draw.cpp.i
.PHONY : src/vendor/imgui/imgui_draw.cpp.i

src/vendor/imgui/imgui_draw.s: src/vendor/imgui/imgui_draw.cpp.s

.PHONY : src/vendor/imgui/imgui_draw.s

# target to generate assembly for a file
src/vendor/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_draw.cpp.s
.PHONY : src/vendor/imgui/imgui_draw.cpp.s

src/vendor/imgui/imgui_impl_glfw.o: src/vendor/imgui/imgui_impl_glfw.cpp.o

.PHONY : src/vendor/imgui/imgui_impl_glfw.o

# target to build an object file
src/vendor/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_impl_glfw.cpp.o
.PHONY : src/vendor/imgui/imgui_impl_glfw.cpp.o

src/vendor/imgui/imgui_impl_glfw.i: src/vendor/imgui/imgui_impl_glfw.cpp.i

.PHONY : src/vendor/imgui/imgui_impl_glfw.i

# target to preprocess a source file
src/vendor/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_impl_glfw.cpp.i
.PHONY : src/vendor/imgui/imgui_impl_glfw.cpp.i

src/vendor/imgui/imgui_impl_glfw.s: src/vendor/imgui/imgui_impl_glfw.cpp.s

.PHONY : src/vendor/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
src/vendor/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_impl_glfw.cpp.s
.PHONY : src/vendor/imgui/imgui_impl_glfw.cpp.s

src/vendor/imgui/imgui_impl_opengl3.o: src/vendor/imgui/imgui_impl_opengl3.cpp.o

.PHONY : src/vendor/imgui/imgui_impl_opengl3.o

# target to build an object file
src/vendor/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_impl_opengl3.cpp.o
.PHONY : src/vendor/imgui/imgui_impl_opengl3.cpp.o

src/vendor/imgui/imgui_impl_opengl3.i: src/vendor/imgui/imgui_impl_opengl3.cpp.i

.PHONY : src/vendor/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
src/vendor/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_impl_opengl3.cpp.i
.PHONY : src/vendor/imgui/imgui_impl_opengl3.cpp.i

src/vendor/imgui/imgui_impl_opengl3.s: src/vendor/imgui/imgui_impl_opengl3.cpp.s

.PHONY : src/vendor/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
src/vendor/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_impl_opengl3.cpp.s
.PHONY : src/vendor/imgui/imgui_impl_opengl3.cpp.s

src/vendor/imgui/imgui_widgets.o: src/vendor/imgui/imgui_widgets.cpp.o

.PHONY : src/vendor/imgui/imgui_widgets.o

# target to build an object file
src/vendor/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_widgets.cpp.o
.PHONY : src/vendor/imgui/imgui_widgets.cpp.o

src/vendor/imgui/imgui_widgets.i: src/vendor/imgui/imgui_widgets.cpp.i

.PHONY : src/vendor/imgui/imgui_widgets.i

# target to preprocess a source file
src/vendor/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_widgets.cpp.i
.PHONY : src/vendor/imgui/imgui_widgets.cpp.i

src/vendor/imgui/imgui_widgets.s: src/vendor/imgui/imgui_widgets.cpp.s

.PHONY : src/vendor/imgui/imgui_widgets.s

# target to generate assembly for a file
src/vendor/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/imgui/imgui_widgets.cpp.s
.PHONY : src/vendor/imgui/imgui_widgets.cpp.s

src/vendor/stb_image/stb_image.o: src/vendor/stb_image/stb_image.cpp.o

.PHONY : src/vendor/stb_image/stb_image.o

# target to build an object file
src/vendor/stb_image/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/stb_image/stb_image.cpp.o
.PHONY : src/vendor/stb_image/stb_image.cpp.o

src/vendor/stb_image/stb_image.i: src/vendor/stb_image/stb_image.cpp.i

.PHONY : src/vendor/stb_image/stb_image.i

# target to preprocess a source file
src/vendor/stb_image/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/stb_image/stb_image.cpp.i
.PHONY : src/vendor/stb_image/stb_image.cpp.i

src/vendor/stb_image/stb_image.s: src/vendor/stb_image/stb_image.cpp.s

.PHONY : src/vendor/stb_image/stb_image.s

# target to generate assembly for a file
src/vendor/stb_image/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/vendor/stb_image/stb_image.cpp.s
.PHONY : src/vendor/stb_image/stb_image.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gui_autogen"
	@echo "... gui"
	@echo "... main"
	@echo "... QtApp/Item.o"
	@echo "... QtApp/Item.i"
	@echo "... QtApp/Item.s"
	@echo "... QtApp/Mainwindow.o"
	@echo "... QtApp/Mainwindow.i"
	@echo "... QtApp/Mainwindow.s"
	@echo "... QtApp/Workspace.o"
	@echo "... QtApp/Workspace.i"
	@echo "... QtApp/Workspace.s"
	@echo "... QtApp/WorkspaceScene.o"
	@echo "... QtApp/WorkspaceScene.i"
	@echo "... QtApp/WorkspaceScene.s"
	@echo "... QtApp/main.o"
	@echo "... QtApp/main.i"
	@echo "... QtApp/main.s"
	@echo "... gui_autogen/mocs_compilation.o"
	@echo "... gui_autogen/mocs_compilation.i"
	@echo "... gui_autogen/mocs_compilation.s"
	@echo "... src/ModelApplication.o"
	@echo "... src/ModelApplication.i"
	@echo "... src/ModelApplication.s"
	@echo "... src/OpenglLayer.o"
	@echo "... src/OpenglLayer.i"
	@echo "... src/OpenglLayer.s"
	@echo "... src/core/Car.o"
	@echo "... src/core/Car.i"
	@echo "... src/core/Car.s"
	@echo "... src/core/ForceGenerator.o"
	@echo "... src/core/ForceGenerator.i"
	@echo "... src/core/ForceGenerator.s"
	@echo "... src/core/MDLParser.o"
	@echo "... src/core/MDLParser.i"
	@echo "... src/core/MDLParser.s"
	@echo "... src/core/Particle.o"
	@echo "... src/core/Particle.i"
	@echo "... src/core/Particle.s"
	@echo "... src/core/Road.o"
	@echo "... src/core/Road.i"
	@echo "... src/core/Road.s"
	@echo "... src/core/TrafficLight.o"
	@echo "... src/core/TrafficLight.i"
	@echo "... src/core/TrafficLight.s"
	@echo "... src/core/Vector.o"
	@echo "... src/core/Vector.i"
	@echo "... src/core/Vector.s"
	@echo "... src/glfw/Window.o"
	@echo "... src/glfw/Window.i"
	@echo "... src/glfw/Window.s"
	@echo "... src/imgui/ImguiLayer.o"
	@echo "... src/imgui/ImguiLayer.i"
	@echo "... src/imgui/ImguiLayer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/opengl/Buffer.o"
	@echo "... src/opengl/Buffer.i"
	@echo "... src/opengl/Buffer.s"
	@echo "... src/opengl/OrtographicCamera.o"
	@echo "... src/opengl/OrtographicCamera.i"
	@echo "... src/opengl/OrtographicCamera.s"
	@echo "... src/opengl/Renderer.o"
	@echo "... src/opengl/Renderer.i"
	@echo "... src/opengl/Renderer.s"
	@echo "... src/opengl/Shader.o"
	@echo "... src/opengl/Shader.i"
	@echo "... src/opengl/Shader.s"
	@echo "... src/opengl/Texture.o"
	@echo "... src/opengl/Texture.i"
	@echo "... src/opengl/Texture.s"
	@echo "... src/opengl/VertexArray.o"
	@echo "... src/opengl/VertexArray.i"
	@echo "... src/opengl/VertexArray.s"
	@echo "... src/opengl/debug.o"
	@echo "... src/opengl/debug.i"
	@echo "... src/opengl/debug.s"
	@echo "... src/pch.o"
	@echo "... src/pch.i"
	@echo "... src/pch.s"
	@echo "... src/vendor/imgui/imgui.o"
	@echo "... src/vendor/imgui/imgui.i"
	@echo "... src/vendor/imgui/imgui.s"
	@echo "... src/vendor/imgui/imgui_demo.o"
	@echo "... src/vendor/imgui/imgui_demo.i"
	@echo "... src/vendor/imgui/imgui_demo.s"
	@echo "... src/vendor/imgui/imgui_draw.o"
	@echo "... src/vendor/imgui/imgui_draw.i"
	@echo "... src/vendor/imgui/imgui_draw.s"
	@echo "... src/vendor/imgui/imgui_impl_glfw.o"
	@echo "... src/vendor/imgui/imgui_impl_glfw.i"
	@echo "... src/vendor/imgui/imgui_impl_glfw.s"
	@echo "... src/vendor/imgui/imgui_impl_opengl3.o"
	@echo "... src/vendor/imgui/imgui_impl_opengl3.i"
	@echo "... src/vendor/imgui/imgui_impl_opengl3.s"
	@echo "... src/vendor/imgui/imgui_widgets.o"
	@echo "... src/vendor/imgui/imgui_widgets.i"
	@echo "... src/vendor/imgui/imgui_widgets.s"
	@echo "... src/vendor/stb_image/stb_image.o"
	@echo "... src/vendor/stb_image/stb_image.i"
	@echo "... src/vendor/stb_image/stb_image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

